# Pipeline to run the HPU tests in DL1 Instance

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "future/*"
      - "refs/tags/*"
pr:
  - "master"
  - "release/*"
  - "future/*"

jobs:
  - job: tests

    # how long to run the job before automatically cancelling
    timeoutInMinutes: "10"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"

    pool: intel-hpus

    workspace:
      clean: all

    steps:
    - bash: |
        apt-get install -y hwinfo
        hwinfo --short
      displayName: 'Instance HW info'

    - bash: |
        pip install . --requirement requirements/extra.txt
        pip install . --requirement requirements/test.txt
      displayName: 'Install dependencies'

    - bash: |
        python -m pytest -sv tests/accelerators/test_hpu.py --forked --junitxml=hpu1_test-results.xml
      displayName: 'Single card HPU test'

    - bash: |
        python -m pytest -sv tests/accelerators/test_hpu.py --forked --hpus 8 --junitxml=hpu8_test-results.xml
      displayName: 'Multi card(8) HPU test'

    - bash: |
        python -m pytest -sv tests/plugins/precision/hpu/test_hpu.py --hmp-bf16 'tests/plugins/precision/hpu/ops_bf16.txt' --hmp-fp32 'tests/plugins/precision/hpu/ops_fp32.txt' --forked --junitxml=hpu1_precision_test-results.xml
      displayName: 'HPU precision test'

    - bash: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        python "pl_examples/hpu_examples/simple_mnist/mnist.py"
      displayName: 'Testing: HPU examples'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'hpu*_test-results.xml'
        testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
      condition: succeededOrFailed()
      displayName: 'Publish test results'
