name: Schema
on: # Trigger the workflow on push or pull request, but only for the master branch
  push: {}
  pull_request:
    branches: [master, "release/*", "future/*"]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pkg
        run: |
          pip install "check-jsonschema>=0.10"

      - name: GH Workflows
        run: check-jsonschema .github/workflows/*.yml --builtin-schema "github-workflows"

      - name: Azure Pipelines
        env:
          SCHEMA_FILE: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.204.0/service-schema.json
        run: check-jsonschema .azure-pipelines/*.yml --schemafile "$SCHEMA_FILE"
